# name of the software
name: Laravel Angular Admin
# current version of the software
version: 0.1.0
# url of the download button
downloadUrl: https://github.com/silverbux/laravel-angular-admin/releases
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/silverbux/laravel-angular-admin

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/silverbux/laravel-angular-admin
  - title: Issues
    url: https://github.com/silverbux/laravel-angular-admin/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: silverbux
  repo: laravel-angular-admin

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap